server:
  port: 7002

#-----------------单机版配置-----------------------
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false # false表示不向注册中心注册自己
#    fetch-registry: false # false表示自己就是注册中心，不需要去检索服务，我的职责是维护服务实例
#    service-url:
#      # 设置与Eureka Server交互的地址，地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#-----------------单机版配置-----------------------

#-----------------集群版配置-----------------------
eureka:
  instance:
    hostname: eureka7002.com #已经通过本地host文件更改，指向127.0.0.1 ip地址
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示自己就是注册中心，不需要去检索服务，我的职责是维护服务实例
    service-url:
      # 设置与Eureka Server交互的地址，地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
#-----------------集群版配置-----------------------
