server:
  port: 8003

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    druid:
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个，
      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-on-borrow: false
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-while-idle: true
      # 指明是否在归还到池中前进行检验，注意: 设置为true后如果要生效,
      #validationQuery参数必须设置为非空字符串
      test-on-return: false
      # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.
      #如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
      validation-query: select 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rumwei.springcloud.entity #所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册到Eureka Server，默认为true
    fetch-registry: true #是否从Eureka Server抓取已有的注册信息，默认true。单节点无所谓，集群必须配置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka 单机版本
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: payment8001 #注册到Eureka Server的实例名称，会在Eureka的页面中显示
    prefer-ip-address: true
