
spring:
  application:
    name: payment-consumer-service-feign
server:
  port: 80
eureka:
  client:
    register-with-eureka: false #不将本服务作为微服务注册进Eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
#设置feign客户端超时时间(OpenFeign默认支持Ribbon)
ribbon:
  ReadTimeout: 5000 #与provider端建立连接所用的时间(5s)，适用于网络状况正常的情况
  ConnectTimeout: 5000 #调用provider服务的超时时间(5s),默认1s
#配合config包中的FeignLogConfig使用
logging:
  level:
    com.rumwei.springcloud.service.PaymentFeignService: debug
